FROM docker.elastic.co/elasticsearch/elasticsearch:7.1.1

HEALTHCHECK --interval=10s --timeout=10s --retries=3 CMD curl --silent --fail localhost:9200/_cluster/health || exit 1

COPY ./dictionaries /usr/share/elasticsearch/config/hunspell
