version: '3'

services:
  frontend:
    image: marvinroesch/book-search-frontend
    ports:
      - "4080:80"
    depends_on:
      backend:
        condition: service_healthy

  backend:
    image: marvinroesch/book-search-backend
    volumes:
      - sessions:/app/.sessions
    environment:
      - ELASTIC_HOST=http://elasticsearch:9200
      - DEFAULT_PASSWORD=booksearcher
      - CRYPTO_KEY=966efc7f2526829ec7580bfb033652555adcc2bd8fb2a250aaa0ced12bbff00b7b60dd0e323f129171a27d66660af93b258eab90507ff28895fb79b459ced1f2 # Must be hexadecimal
      - DB_CONNECTION=jdbc:postgresql://db/booksearch
      - DB_DRIVER=org.postgresql.Driver
      - DB_USERNAME=booksearch
      - DB_PASSWORD=b00kse4rch
      - DB_MIGRATION_USERNAME=booksearch_migrations
      - DB_MIGRATION_PASSWORD=migr4tion5
    depends_on:
      elasticsearch:
        condition: service_healthy
      db:
        condition: service_healthy

  elasticsearch:
    image: marvinroesch/book-search-elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  db:
    image: postgres:12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./database-init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - DB_MIGRATION_USER=booksearch_migrations
      - DB_MIGRATION_PASSWORD=migr4tion5
      - DB_DATA_USER=booksearch
      - DB_DATA_PASSWORD=b00kse4rch

volumes:
  sessions:
  esdata:
  dbdata:
